version: "3.7"
services:
  api:
    image: "marvik_api:latest"
    tty: true
    depends_on:
        - db
    ports:
      - 8000:80
    env_file:
      - ../.dev.env
    volumes:
      - ../src/:/app/marvik_api
    command: bash #-c "while true; do sleep 1; done"

  db:
    image: "postgres:13"
    env_file:
      - ../.dev.env
    volumes:
      - app-db-data-dev:/var/lib/postgresql/data/pgdata

volumes:
  app-db-data-dev:

networks:
  default:
    external:
      name: $NETWORK_NAME
