version: "3.7"
services:
  api:
    image: "marvik_api:latest"
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /start-reload.sh

  db:
    image: "postgres:13"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
  default:
    external:
      name: $NETWORK_NAME
